// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: protos/editor.proto

package editor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchUpdatesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUpdatesReq) Reset() {
	*x = FetchUpdatesReq{}
	mi := &file_protos_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUpdatesReq) ProtoMessage() {}

func (x *FetchUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUpdatesReq.ProtoReflect.Descriptor instead.
func (*FetchUpdatesReq) Descriptor() ([]byte, []int) {
	return file_protos_editor_proto_rawDescGZIP(), []int{0}
}

type FetchUpdatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchUpdatesReply) Reset() {
	*x = FetchUpdatesReply{}
	mi := &file_protos_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchUpdatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchUpdatesReply) ProtoMessage() {}

func (x *FetchUpdatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchUpdatesReply.ProtoReflect.Descriptor instead.
func (*FetchUpdatesReply) Descriptor() ([]byte, []int) {
	return file_protos_editor_proto_rawDescGZIP(), []int{1}
}

type Ops struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ops) Reset() {
	*x = Ops{}
	mi := &file_protos_editor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ops) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ops) ProtoMessage() {}

func (x *Ops) ProtoReflect() protoreflect.Message {
	mi := &file_protos_editor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ops.ProtoReflect.Descriptor instead.
func (*Ops) Descriptor() ([]byte, []int) {
	return file_protos_editor_proto_rawDescGZIP(), []int{2}
}

type PushOpsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOpsReply) Reset() {
	*x = PushOpsReply{}
	mi := &file_protos_editor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOpsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOpsReply) ProtoMessage() {}

func (x *PushOpsReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_editor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOpsReply.ProtoReflect.Descriptor instead.
func (*PushOpsReply) Descriptor() ([]byte, []int) {
	return file_protos_editor_proto_rawDescGZIP(), []int{3}
}

var File_protos_editor_proto protoreflect.FileDescriptor

var file_protos_editor_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x05, 0x0a,
	0x03, 0x4f, 0x70, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x70, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x62, 0x0a, 0x06, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x36,
	0x0a, 0x0c, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x10,
	0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x70,
	0x73, 0x12, 0x04, 0x2e, 0x4f, 0x70, 0x73, 0x1a, 0x0d, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x70,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_editor_proto_rawDescOnce sync.Once
	file_protos_editor_proto_rawDescData []byte
)

func file_protos_editor_proto_rawDescGZIP() []byte {
	file_protos_editor_proto_rawDescOnce.Do(func() {
		file_protos_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_editor_proto_rawDesc), len(file_protos_editor_proto_rawDesc)))
	})
	return file_protos_editor_proto_rawDescData
}

var file_protos_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_editor_proto_goTypes = []any{
	(*FetchUpdatesReq)(nil),   // 0: FetchUpdatesReq
	(*FetchUpdatesReply)(nil), // 1: FetchUpdatesReply
	(*Ops)(nil),               // 2: Ops
	(*PushOpsReply)(nil),      // 3: PushOpsReply
}
var file_protos_editor_proto_depIdxs = []int32{
	0, // 0: Editor.FetchUpdates:input_type -> FetchUpdatesReq
	2, // 1: Editor.PushOps:input_type -> Ops
	1, // 2: Editor.FetchUpdates:output_type -> FetchUpdatesReply
	3, // 3: Editor.PushOps:output_type -> PushOpsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_editor_proto_init() }
func file_protos_editor_proto_init() {
	if File_protos_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_editor_proto_rawDesc), len(file_protos_editor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_editor_proto_goTypes,
		DependencyIndexes: file_protos_editor_proto_depIdxs,
		MessageInfos:      file_protos_editor_proto_msgTypes,
	}.Build()
	File_protos_editor_proto = out.File
	file_protos_editor_proto_goTypes = nil
	file_protos_editor_proto_depIdxs = nil
}
